Repository PingCAP-QE/ee-ops, pull requests merged in 2022-12, with the labels that each got.

#305 fix(apps/prod/ats): fix cache.config to avoid 404 when request to /gomod
  apps/prod/ats/config-override/cache.config
Labels: approved

#307 fix(apps/prod/greenhouse): fix evicting args for local path device mount
  apps/prod/greenhouse/release.yaml
Labels: approved

#308 feat(clusters): add lark notifies
  clusters/prod/flux-system/notification.yaml
  clusters/staging/flux-system/notification.yaml
Labels: approved

#309 fix(apps/staging/jenkins/pre): fix pipeline cache shrink job
  apps/staging/jenkins/pre/obc/cronjobs.yaml
Labels: approved

#310 fix(apps/prod/goproxy): adjust upstream goproxy
  apps/prod/goproxy/deployment.yaml
Labels: lgtm, approved

#312 feat(apps/prod/greenhouse): increase block pvc size to 4T
  apps/prod/greenhouse/release.yaml
Labels: approved

#313 feat(infrastructure/prod/rook-ceph): bump rook-ceph version to v1.10.0
  infrastructure/prod/rook-ceph/release-cluster.yaml
  infrastructure/prod/rook-ceph/release-operator.yaml
Labels: approved

#314 Revert "feat(infrastructure/prod/rook-ceph): bump rook-ceph version to v1.10.0"
  infrastructure/prod/rook-ceph/release-cluster.yaml
  infrastructure/prod/rook-ceph/release-operator.yaml
Labels: approved

#315 feat(infrastructure/prod/rook-ceph): add a host disk
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#316 feat(infrastructure/prod/rook-ceph): add another three host disks
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#317 feat(apps/prod/greenhouse): increase block pvc size to 8T
  apps/prod/greenhouse/release.yaml
Labels: approved

#318 feat(infrastructure/prod/rook-ceph): add another three host disks
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#319 feat(apps/prod/jenkins/release): update bfa to hacked edition
  apps/prod/jenkins/release/values-controller-plugins.yaml
  apps/staging/jenkins/release/release.yaml
  apps/staging/jenkins/release/values-controller-plugins.yaml
Labels: approved

#320 feat(apps/prod/ats): enable ingress for ats service
  apps/prod/ats/release.yaml
Labels: approved

#322 ci(renovate): add auto update for helm charts
  .github/renovate.json
  charts/greenhouse/values.yaml
  charts/prow/Chart.yaml
  infrastructure/staging/rook-ceph/release-cluster.yaml
  infrastructure/staging/rook-ceph/release-operator.yaml
Labels: approved

#323 refactor(apps/staging/prow/post/configs/jobs): reduce nested kustomization files
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/kustomization.yaml
  apps/staging/prow/post/configs/jobs/PingCAP-QE/kustomization.yaml
  apps/staging/prow/post/configs/jobs/kustomization.yaml
Labels: approved

#325 fix(renovate): fix renovate.json
  .github/renovate.json
Labels: approved

#326 fix(apps/prod/jenkins/post/tidb): increase bazel remote timeout from 10s to 30s
  apps/prod/ats/config-override/cache.config
  apps/prod/ats/config-override/records.config
  apps/prod/jenkins/post/tidb/files/bazel
  apps/staging/ats/config-override/records.config
Labels: approved

#329 fix(cluster/staging2): fix kustomization
  clusters/staging2/flux-system/gotk-sync.yaml
Labels: approved

#331 feat(cluster/staging): bump rook-ceph to v1.10.7
  infrastructure/staging/rook-ceph/release-cluster.yaml
  infrastructure/staging/rook-ceph/release-operator.yaml
Labels: approved

#330 chore(infrastructure/staging2/nginx): using special ports as nginx node ports
  infrastructure/_base/sources/git-repo-prometheus-operator.yaml
  infrastructure/staging2/nginx/release.yaml
Labels: approved

#332 refactor(infrastructure): delete useless secret
  README.md
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#334 feat(charts/prow-crd): add chart prow-crd
  charts/prow-crd/.helmignore
  charts/prow-crd/Chart.yaml
  charts/prow-crd/templates/_helpers.tpl
  charts/prow-crd/templates/prowjob-crd.yaml
  charts/prow-crd/values.yaml
Labels: approved

#337 feat(charts/prow-crd): add chart prow-crd
  .github/workflows/charts_release.yaml
  charts/prow/charts/prow-crd/.helmignore
  charts/prow/charts/prow-crd/Chart.yaml
  charts/prow/charts/prow-crd/templates/_helpers.tpl
  charts/prow/charts/prow-crd/templates/prowjob-crd.yaml
  charts/prow/charts/prow-crd/values.yaml
Labels: approved

#338 feat(charts/prow-crd): add chart prow-crd
  charts/prow-crd/Chart.yaml
Labels: approved

#333 feat(apps/staging/prow): bump prow components to v20221216-06fc803e5c
  .github/workflows/charts_release.yaml
  apps/_base/kustomization.yaml
  apps/_base/sources/helm-repo-ee-ops.yaml
  apps/_base/sources/kustomization.yaml
  apps/prod/kustomization.yaml
  apps/staging/kustomization.yaml
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/charts/prow-crd/.helmignore
  charts/prow/charts/prow-crd/Chart.yaml
  charts/prow/charts/prow-crd/templates/_helpers.tpl
  charts/prow/charts/prow-crd/templates/prowjob-crd.yaml
  charts/prow/charts/prow-crd/values.yaml
Labels: approved

#339 ci(charts/prow): fix ct install
  .github/workflows/charts_test-prow.yaml
Labels: approved

#340 feat(charts/prow): support third-plugins deployments
  charts/prow/templates/third-plugins/deployment.yaml
  charts/prow/values.yaml
Labels: approved

#342 feat(charts/prow): support third-plugins deployments
  charts/prow/templates/NOTES.txt
  charts/prow/templates/_helpers.tpl
  charts/prow/templates/third-plugins/deployment.yaml
  charts/prow/templates/third-plugins/hpa.yaml
  charts/prow/templates/third-plugins/ingress.yaml
  charts/prow/templates/third-plugins/service.yaml
  charts/prow/templates/third-plugins/serviceaccount.yaml
  charts/prow/values.yaml
Labels: approved

#343 chore(charts/prow): bump version to v0.4.0
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
Labels: approved

#347 ci(renovate): add regex rules
  .github/renovate.json
  apps/staging/jenkins/release/values-controller.yaml
  infrastructure/staging/rook-ceph/release-cluster.yaml
  infrastructure/staging/rook-ceph/release-operator.yaml
  infrastructure/staging2/rook-ceph/release-cluster.yaml
  infrastructure/staging2/rook-ceph/release-operator.yaml
Labels: approved

#345 refactor(charts/prow): split minio from prow
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/config/default-prow-config.yaml.tpl
  charts/prow/templates/_helpers.tpl
  charts/prow/templates/components/crier/deployment.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/ghproxy/deployment.yaml
  charts/prow/templates/components/status-reconciler/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/templates/secret-persistent.yaml
  charts/prow/templates/secret-s3.yaml
  charts/prow/values.yaml
Labels: approved

#348 ci(verify2): fix decorate
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
Labels: approved

#349 feat(charts/prow): add bucketname support
  apps/staging/prow/post.yaml
  apps/staging/prow/post/configs/config.yaml
  apps/staging/prow/pre/kustomization.yaml
  apps/staging/prow/pre/obc.yaml
  apps/staging/prow/release.yaml
  apps/staging/prow/release/kustomization.yaml
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/config/default-prow-config.yaml.tpl
  charts/prow/templates/_helpers.tpl
  charts/prow/templates/components/crier/deployment.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/status-reconciler/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/values.yaml
Labels: approved

#351 fix(apps/staging/prow): fix conflict of prow chart version
  apps/staging/prow/post/configs/config.yaml
Labels: approved

#350 fix(apps/staging/prow): add needs-rebase external plugins and upgrade prow chart
  apps/staging/prow/post/configs/config.yaml
  apps/staging/prow/post/configs/plugins.yaml
  apps/staging/prow/release/release.yaml
Labels: approved

#353 fix(apps/staging/prow): fix bucket region
  apps/staging/prow/release/release.yaml
Labels: approved

#354 fix(apps/staging/prow): disable needs-rebase
  apps/staging/prow/release/release.yaml
Labels: approved

#355 feat(charts/prow): support global value overrides in third plugins
  charts/prow/Chart.yaml
  charts/prow/templates/components/crier/deployment.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/ghproxy/deployment.yaml
  charts/prow/templates/components/hook/deployment.yaml
  charts/prow/templates/components/horologium/deployment.yaml
  charts/prow/templates/components/jenkins-operator/deployment.yaml
  charts/prow/templates/components/pipeline/deployment.yaml
  charts/prow/templates/components/prow-controller-manager/deployment.yaml
  charts/prow/templates/components/sinker/deployment.yaml
  charts/prow/templates/components/status-reconciler/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/templates/third-plugins/deployment.yaml
  charts/prow/values.yaml
Labels: approved

#356 chore(apps/staging/prow/release): bump prow chart to v0.6.1
  apps/staging/prow/release/release.yaml
Labels: approved

#357 fix(apps/staging/prow): add needs-rebase external plugins and upgrade prow chart
  apps/staging/prow/release/release.yaml
Labels: approved

#358 fix(charts/prow): fix third plugin deployment
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/third-plugins/deployment.yaml
Labels: approved

#359 fix(charts/prow): insert the default env
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/third-plugins/deployment.yaml
  infrastructure/staging/monitoring/operator.yaml
Labels: approved, do-not-merge/hold

#360 Revert "fix(charts/prow): insert the default env"
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/third-plugins/deployment.yaml
  infrastructure/staging/monitoring/operator.yaml
Labels: approved

#361 Revert "fix(charts/prow): insert the default env (#359)"
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/third-plugins/service.yaml
  charts/prow/values.yaml
Labels: approved

#362 fix(apps/staging/prow): expose service for needs-rebase
  apps/staging/prow/release/release.yaml
Labels: approved

#363 feat(apps/dev): add dev env gitops
  apps/dev/kustomization.yaml
  apps/dev/namespace.yaml
  apps/dev/prow/kustomization.yaml
  apps/dev/prow/post.yaml
  apps/dev/prow/post/configs/README.md
  apps/dev/prow/post/configs/config.yaml
  apps/dev/prow/post/configs/kustomization.yaml
  apps/dev/prow/post/configs/labels.yaml
  apps/dev/prow/post/configs/plugins.yaml
  apps/dev/prow/post/kustomization.yaml
  apps/dev/prow/pre.yaml
  apps/dev/prow/pre/kustomization.yaml
  apps/dev/prow/pre/namespace-test-pods.yaml
  apps/dev/prow/pre/rbac-test-pods-k8s-pod-full.yaml
  apps/dev/prow/release.yaml
  apps/dev/prow/release/kustomization.yaml
  apps/dev/prow/release/release.yaml
  clusters/dev/README.md
  clusters/dev/apps.yaml
Labels: approved

#364 fix(apps/dev/prow): fix substitute of gcs credentials
  apps/dev/prow/release.yaml
  apps/dev/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/config/default-prow-config.yaml.tpl
  charts/prow/templates/_helpers.tpl
  charts/prow/templates/components/crier/deployment.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/status-reconciler/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/templates/secret-persistent.yaml
  charts/prow/values.yaml
  clusters/dev/README.md
Labels: approved

#365 fix(apps/dev/prow): fix third plugin service type
  apps/dev/prow/release/release.yaml
Labels: approved

#366 fix(apps/dev/prow, apps/staging/prow): fix third plugin configuration
  apps/dev/prow/release/release.yaml
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-label-sync.yaml
  apps/staging/prow/release/release.yaml
Labels: approved

#367 feat(apps/dev/prow): update ingress to static ip
  apps/dev/prow/release/release.yaml
  clusters/dev/README.md
Labels: approved

#368 fix(apps/dev/prow): fix ingress to static ip, disable in helm chart installation
  apps/dev/prow/post.yaml
  apps/dev/prow/release/gce-ingress.yaml
  apps/dev/prow/release/kustomization.yaml
  apps/dev/prow/release/release.yaml
Labels: approved

#369 fix(apps/dev/prow): fix ingress to static ip, disable in helm chart installation
  apps/dev/prow/release/gce-ingress.yaml
Labels: approved

#370 fix(apps/dev/prow): fix ingress to static ip, disable in helm chart installation
  apps/dev/prow/release/kustomization.yaml
  apps/staging/prow/release/kustomization.yaml
Labels: approved

#371 fix(apps/dev/prow): add frontend config for gce ingress
  apps/dev/prow/release/frontend-config.yaml
  apps/dev/prow/release/gce-ingress.yaml
  apps/dev/prow/release/kustomization.yaml
Labels: approved

#372 feat(apps/dev/prow): add tichi-web and ti-community-owners external plugins or components
  apps/dev/prow/post.yaml
  apps/dev/prow/post/configs/config.yaml
  apps/dev/prow/release/gce-ingress.yaml
  apps/dev/prow/release/release.yaml
  apps/staging/prow/post.yaml
  apps/staging/prow/post/configs/config.yaml
Labels: approved

#373 fix(apps/dev/prow): fix ingress
  apps/dev/prow/release/gce-ingress.yaml
Labels: approved

#374 fix(apps/dev/prow): fix ingress
  apps/dev/prow/release/release.yaml
Labels: approved

#375 fix(charts/prow): fix third plugins
  apps/dev/prow/release/release.yaml
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/third-plugins/deployment.yaml
Labels: approved

#376 feat(apps/dev/prow/post): add cron job
  apps/dev/prow/post/configs/config.yaml
  apps/dev/prow/post/configs/external_plugins_config.yaml
  apps/dev/prow/post/configs/kustomization.yaml
  apps/dev/prow/post/configs/labels.yaml
  apps/dev/prow/post/configs/plugins.yaml
  apps/dev/prow/post/kustomization.yaml
  apps/dev/prow/post/label-sync-cronjob.yaml
  apps/dev/prow/release/release.yaml
Labels: approved

#377 feat(apps/dev/prow/post): fix post kustomization path
  apps/dev/prow/post.yaml
Labels: approved

#380 chore(apps/prod/greenhouse): increase greenhouse disk size to 10TB
  apps/prod/greenhouse/release.yaml
Labels: approved
