Repository PingCAP-QE/ee-ops, pull requests merged in 2023-04, with the labels that each got.

#445 feat(apps/prod): add another jenkins stack for gitee projects
  apps/prod/jenkins-gitee/kustomization.yaml
  apps/prod/jenkins-gitee/post.yaml
  apps/prod/jenkins-gitee/post/cronjob-go-caches.yaml
  apps/prod/jenkins-gitee/post/kustomization.yaml
  apps/prod/jenkins-gitee/post/pvc.yaml
  apps/prod/jenkins-gitee/pre.yaml
  apps/prod/jenkins-gitee/pre/cronjobs.yaml
  apps/prod/jenkins-gitee/pre/kustomization.yaml
  apps/prod/jenkins-gitee/pre/obc.yaml
  apps/prod/jenkins-gitee/pre/obc/obc.yaml
  apps/prod/jenkins-gitee/pre/secret.yaml
  apps/prod/jenkins-gitee/pre/secret/cache-secret.yaml
  apps/prod/jenkins-gitee/release.yaml
  apps/prod/jenkins-gitee/release/README.md
  apps/prod/jenkins-gitee/release/kustomization.yaml
  apps/prod/jenkins-gitee/release/kustomize-config.yaml
  apps/prod/jenkins-gitee/release/namespace-agent.yaml
  apps/prod/jenkins-gitee/release/release.yaml
  apps/prod/jenkins-gitee/release/values-JCasC.yaml
  apps/prod/jenkins-gitee/release/values-agent.yaml
  apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
  apps/prod/jenkins-gitee/release/values-controller.yaml
  apps/prod/jenkins-gitee/release/values-persistence.yaml
  apps/prod/jenkins-gitee/release/values-service-account.yaml
  apps/prod/kustomization.yaml
Labels: lgtm, approved

#446 fix(apps/prod/jenkins-gitee/release): bump version for jenkins server and fix plugin version conflicts
  apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
  apps/prod/jenkins-gitee/release/values-controller.yaml
Labels: approved

#447 fix(apps/prod/jenkins-gitee/release): add init container to fix logs dir issue
  apps/prod/jenkins-gitee/release/values-controller.yaml
Labels: approved

#443 feat(apps/staging/tekton/configs/tasks): add kaniko task
  apps/staging/tekton/configs/pipelines/kaniko-build.yaml
  apps/staging/tekton/configs/tasks/ko.yaml
  apps/staging/tekton/configs/tasks/kustomization.yaml
  apps/staging/tekton/configs/tasks/multi-arch-image-push.yaml
Labels: approved

#448 fix(apps/prod/jenkins-gitee/release): add readonly role and user
  apps/prod/jenkins-gitee/release/values-JCasC.yaml
  apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
Labels: approved

#449 fix(apps/prod/jenkins-gitee/release): fix `additionalExistingSecrets`
  apps/prod/jenkins-gitee/release/values-JCasC.yaml
Labels: approved

#451 feat(apps/prod/jenkins-gitee/release): add `gitee` plugin
  apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
Labels: approved

#453 fix(apps/prod/jenkins-gitee/release): fix job DSL dir path for seed job
  apps/prod/jenkins-gitee/release/values-JCasC.yaml
Labels: approved

#455 feat(apps/staging/harbor): add harbor to staging
  apps/staging/harbor/kustomization.yaml
  apps/staging/harbor/release.yaml
  apps/staging/harbor/release/kustomization.yaml
  apps/staging/harbor/release/release.yaml
  apps/staging/harbor/release/values.yaml
  apps/staging/kustomization.yaml
Labels: lgtm, approved

#456 feat(apps/prod/jenkins-gitee/release): add `ssh-agent` plugin
  apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
Labels: approved

#460 feat(apps/prod/jenkins-gitee/release): add gitee connection
  apps/prod/jenkins-gitee/release/values-JCasC.yaml
Labels: approved

#462 fix(apps/staging/harbor): use correct values config for harbor
  apps/staging/harbor/release/release.yaml
Labels: lgtm, approved

#430 feat(prod/jenkins): add plugin ssh-agent
  apps/prod/jenkins/release/values-controller-plugins.yaml
Labels: lgtm, approved

#444 config(apps/prod/jenkins): add some tokens
  apps/prod/jenkins/release/values-JCasC.yaml
Labels: lgtm, do-not-merge/hold

#463 fix(apps/prod/jenkins/release): bump controller to v2.387.2
  apps/prod/jenkins/release/values-controller-plugins.yaml
  apps/prod/jenkins/release/values-controller.yaml
Labels: approved

#461 feat: deploy tibuild
  apps/prod/tibuild/deployment.yaml
  apps/prod/tibuild/ingress.yaml
  apps/prod/tibuild/kustomization.yaml
  apps/prod/tibuild/service.yaml
Labels: lgtm, approved

#469 feat(apps/prod/jenkins-gitee): add `lock-resource` plugin and add cred for github repos
  apps/prod/jenkins-gitee/release/values-JCasC.yaml
  apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
Labels: approved

#472 fix(apps/staging/jenkins/release): fix plugin conflicts
  apps/staging/jenkins/release/values-controller-plugins.yaml
Labels: approved

#473 fix(apps/dev/prow/release): fix port for chatgpt external plugin
  apps/dev/prow/release/release.yaml
Labels: approved

#474 feat(chats/prow): auto generate the webhook hmac token and oauth cookie secret when not setted
  charts/prow/Chart.yaml
  charts/prow/templates/components/prow-controller-manager/role-pod.yaml
  charts/prow/templates/secret-github.yaml
  charts/prow/templates/secret-hmac.yaml
  charts/prow/values.yaml
Labels: approved

#477 fix(apps/staging/prow/release): fix hmac token issue
  apps/staging/prow/release/release.yaml
Labels: approved

#478 fix(apps/staging/prow/release): fix hmac token issue
  apps/staging/prow/release/release.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/secret-hmac.yaml
Labels: approved

#479 fix(apps/staging/prow/release): fix port for chatgpt external plugin
  apps/staging/prow/release/release.yaml
Labels: approved

#481 chore(apps/staging/prow/post): enable chatgpt external plugin for `pingcap-qe/tirelease` repo
  apps/staging/prow/post/configs/plugins.yaml
Labels: lgtm, approved

#482 feat(apps/prod/jenkins-gitee): move out jenkins-gitee to other repos
  apps/prod/jenkins-gitee.yaml
  apps/prod/jenkins-gitee/kustomization.yaml
  apps/prod/jenkins-gitee/post.yaml
  apps/prod/jenkins-gitee/post/cronjob-go-caches.yaml
  apps/prod/jenkins-gitee/post/kustomization.yaml
  apps/prod/jenkins-gitee/post/pvc.yaml
  apps/prod/jenkins-gitee/pre.yaml
  apps/prod/jenkins-gitee/pre/cronjobs.yaml
  apps/prod/jenkins-gitee/pre/kustomization.yaml
  apps/prod/jenkins-gitee/pre/obc.yaml
  apps/prod/jenkins-gitee/pre/obc/obc.yaml
  apps/prod/jenkins-gitee/pre/secret.yaml
  apps/prod/jenkins-gitee/pre/secret/cache-secret.yaml
  apps/prod/jenkins-gitee/release.yaml
  apps/prod/jenkins-gitee/release/README.md
  apps/prod/jenkins-gitee/release/kustomization.yaml
  apps/prod/jenkins-gitee/release/kustomize-config.yaml
  apps/prod/jenkins-gitee/release/namespace-agent.yaml
  apps/prod/jenkins-gitee/release/release.yaml
  apps/prod/jenkins-gitee/release/values-JCasC.yaml
  apps/prod/jenkins-gitee/release/values-agent.yaml
  apps/prod/jenkins-gitee/release/values-controller-plugins.yaml
  apps/prod/jenkins-gitee/release/values-controller.yaml
  apps/prod/jenkins-gitee/release/values-persistence.yaml
  apps/prod/jenkins-gitee/release/values-service-account.yaml
  apps/prod/kustomization.yaml
Labels: lgtm, approved

#483 refactor(charts/prow): split crd from chart
  .github/workflows/charts_test-prow.yaml
  charts/prow-crd/.helmignore
  charts/prow-crd/Chart.yaml
  charts/prow-crd/templates/_helpers.tpl
  charts/prow-crd/templates/prowjob-crd.yaml
  charts/prow-crd/values.yaml
  charts/prow/Chart.yaml
Labels: approved

#484 refactor(apps/dev,apps/staging): upgrade prow to standalone mode
  apps/_crds/prow/kustomization.yaml
  apps/dev/kustomization.yaml
  apps/dev/prow-crd.yaml
  apps/dev/prow/release/release.yaml
  apps/staging/kustomization.yaml
  apps/staging/prow-crd.yaml
  apps/staging/prow/release/release.yaml
Labels: approved

#485 fix: delete staging2 env
  apps/staging2/kustomization.yaml
  apps/staging2/namespace.yaml
  clusters/staging2/README.md
  clusters/staging2/apps.yaml
  clusters/staging2/flux-system/gotk-components.yaml
  clusters/staging2/flux-system/gotk-sync.yaml
  clusters/staging2/flux-system/kustomization.yaml
  clusters/staging2/flux-system/notification.yaml
  clusters/staging2/infrastructure.yaml
  infrastructure/staging2/kustomization.yaml
  infrastructure/staging2/monitoring/kustomization.yaml
  infrastructure/staging2/monitoring/operator.yaml
  infrastructure/staging2/monitoring/stack.yaml
  infrastructure/staging2/nginx/kustomization.yaml
  infrastructure/staging2/nginx/namespace.yaml
  infrastructure/staging2/nginx/release.yaml
  infrastructure/staging2/rook-ceph/kustomization.yaml
  infrastructure/staging2/rook-ceph/namespace.yaml
  infrastructure/staging2/rook-ceph/release-cluster.yaml
  infrastructure/staging2/rook-ceph/release-operator.yaml
Labels: approved

#429 feat(staging/jenkins): add plugin ssh-agent
  apps/staging/jenkins/release/values-controller-plugins.yaml
Labels: lgtm, approved

#468 feat(clusters/gcp): init gitops for prow gcp prod cluster
  apps/gcp/kustomization.yaml
  apps/gcp/namespace.yaml
  apps/gcp/prow/kustomization.yaml
  apps/gcp/prow/post.yaml
  apps/gcp/prow/pre.yaml
  apps/gcp/prow/pre/kustomization.yaml
  apps/gcp/prow/pre/namespace-test-pods.yaml
  apps/gcp/prow/pre/rbac-test-pods-k8s-pod-full.yaml
  apps/gcp/prow/release.yaml
  apps/gcp/prow/release/frontend-config.yaml
  apps/gcp/prow/release/gce-ingress.yaml
  apps/gcp/prow/release/kustomization.yaml
  apps/gcp/prow/release/release.yaml
  clusters/gcp/README.md
  clusters/gcp/apps.yaml
  clusters/gcp/flux-system/gotk-components.yaml
  clusters/gcp/flux-system/gotk-sync.yaml
  clusters/gcp/flux-system/kustomization.yaml
  clusters/gcp/sources.yaml
Labels: approved

#487 fix(apps/gcp/prow/post): using new path for prow jobs.
  apps/gcp/prow/post/ci-jobs.yaml
Labels: lgtm, approved

#488 Test for plugin
  README.md
Labels: approved

#489 Revert "Test for plugin"
  README.md
Labels: approved

#490 fix(apps/gcp/prow/release): bump ti-* plugin image to v2.4.2
  apps/gcp/prow/post/post.yaml
  apps/gcp/prow/release/release.yaml
Labels: approved

#491 chore(apps/gcp/prow/release): update deployment for jenkins operator to skip report
  apps/gcp/prow/release/release.yaml
Labels: approved

#492 Revert "chore(apps/gcp/prow/release): update deployment for jenkins operator to skip report"
  apps/gcp/prow/release/release.yaml
Labels: approved

#494 chore: comment out test job
  charts/prow/Chart.yaml
  charts/prow/values.yaml
Labels: approved

#495 chore(apps/dev/prow/release): bump third party ti-community-* to v2.4.2
  apps/dev/prow/release/release.yaml
Labels: approved

#497 chore(apps/gcp/prow/release): bump prow release to v0.8.1
  apps/gcp/prow/release/release.yaml
Labels: approved, do-not-merge/hold

#498 feat(apps/staging/sec-server): deploy sec service
  apps/staging/sec-server/deployment.yaml
  apps/staging/sec-server/kustomization.yaml
  apps/staging/sec-server/rbac.yaml
  apps/staging/sec-server/service.yaml
  apps/staging/sec-service.yaml
  apps/staging/sec-service/kustomization.yaml
  apps/staging/sec-service/namespace.yaml
  apps/staging/sec-service/rbac.yaml
  apps/staging/sec-service/redis/deployment.yaml
  apps/staging/sec-service/redis/kustomization.yaml
  apps/staging/sec-service/redis/pvc.yaml
  apps/staging/sec-service/redis/service.yaml
  apps/staging/sec-service/sec-agent/deployment.yaml
  apps/staging/sec-service/sec-agent/kustomization.yaml
  apps/staging/sec-service/sec-server/deployment.yaml
  apps/staging/sec-service/sec-server/kustomization.yaml
Labels: approved

#499 feat(apps/staging/sec-server): deploy sec service
  apps/staging/kustomization.yaml
  apps/staging/sec-service.yaml
Labels: approved

#500 fix(apps/staging/sec-server): fix substitute for kustomization sec-service
  apps/staging/sec-service.yaml
Labels: approved

#501 feat(apps/staging/prow): upgrade to new chatgpt plugin
  apps/staging/prow/post/configs/plugins.yaml
  apps/staging/prow/release/release.yaml
Labels: approved

#502 fix(apps/staging/prow): fix chatgpt container args
  apps/staging/prow/release/release.yaml
Labels: approved

#505 fix(apps/staging/prow): delete white space in yaml
  apps/staging/prow/post/configs/config.yaml
Labels: approved

#506 fix(apps/staging/prow/post): usging merge behavior for openai config
  apps/staging/prow/post/configs/kustomization.yaml
  apps/staging/prow/post/configs/third-plugins/kustomization.yaml
  apps/staging/prow/pre/chatgpt/tasks.yaml
  apps/staging/prow/pre/kustomization.yaml
  apps/staging/prow/release/kustomization.yaml
Labels: approved, size/S

#504 feat(apps/gcp/prow): add deployment for openai plugin
  apps/gcp/prow/pre/chatgpt/tasks.yaml
  apps/gcp/prow/pre/kustomization.yaml
  apps/gcp/prow/release/release.yaml
Labels: approved, size/M
