Repository PingCAP-QE/ee-ops, pull requests merged in 2023-08, with the labels that each got.

#653 feat(apps/prod/jenkins-beta): add a jenkins-beta for debug test
  apps/prod/jenkins-beta/kustomization.yaml
  apps/prod/jenkins-beta/post.yaml
  apps/prod/jenkins-beta/post/_base/kustomization.yaml
  apps/prod/jenkins-beta/post/_base/rbac.yaml
  apps/prod/jenkins-beta/pre.yaml
  apps/prod/jenkins-beta/pre/kustomization.yaml
  apps/prod/jenkins-beta/pre/obc.yaml
  apps/prod/jenkins-beta/pre/obc/obc.yaml
  apps/prod/jenkins-beta/pre/secret.yaml
  apps/prod/jenkins-beta/pre/secret/cache-secret.yaml
  apps/prod/jenkins-beta/release.yaml
  apps/prod/jenkins-beta/release/README.md
  apps/prod/jenkins-beta/release/kustomization.yaml
  apps/prod/jenkins-beta/release/kustomize-config.yaml
  apps/prod/jenkins-beta/release/namespace-agent.yaml
  apps/prod/jenkins-beta/release/release.yaml
  apps/prod/jenkins-beta/release/values-JCasC.yaml
  apps/prod/jenkins-beta/release/values-agent.yaml
  apps/prod/jenkins-beta/release/values-controller-plugins.yaml
  apps/prod/jenkins-beta/release/values-controller.yaml
  apps/prod/jenkins-beta/release/values-persistence.yaml
  apps/prod/jenkins-beta/release/values-service-account.yaml
Labels: lgtm, approved, size/XXL

#657 feat(apps/prod): add jenkins-beta
  apps/prod/kustomization.yaml
Labels: lgtm, approved, size/XS

#658 fix(apps/prod/jenkins-beta): correct nodeselector conf
  apps/prod/jenkins-beta/release/namespace-agent.yaml
  apps/prod/jenkins-beta/release/values-agent.yaml
Labels: lgtm, approved, size/XS

#659 fix(apps/prod/jenkins-beta): remove useless post step
  apps/prod/jenkins-beta/kustomization.yaml
  apps/prod/jenkins-beta/post.yaml
  apps/prod/jenkins-beta/post/_base/kustomization.yaml
  apps/prod/jenkins-beta/post/_base/rbac.yaml
Labels: lgtm, approved, size/M

#663 feat(apps/prod/jenkins-beta): add node affinity
  apps/prod/jenkins-beta/release/values-controller.yaml
Labels: lgtm, approved, size/S

#646 fix(apps/gcp/prow/release): bump hook image to `v20230719-dcd9b36`
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#664 Revert "fix(apps/gcp/prow/release): bump hook image to `v20230719-dcd9b36`"
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#665 Revert "Revert "fix(apps/gcp/prow/release): bump hook image to `v20230719-dcd9b36`""
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#666 Revert "fix(apps/gcp/prow/release): bump hook image to `v20230719-dcd9b36`"
  apps/gcp/prow/release/release.yaml
Labels: lgtm, approved, size/XS

#667 fix(apps/gcp/prow/release): bump hook image to `v20230808-5546ede`
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#668 fix(apps/dev/prow/release): bump hook image to `v20230808-5546ede`
  apps/dev/prow/release/release.yaml
Labels: approved, size/XS

#669 Update release.yaml
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#672 fix: tibuild support dot in branch name
  apps/prod/tibuild/deployment.yaml
Labels: lgtm, approved, size/XS
