Repository PingCAP-QE/ee-ops, pull requests merged in 2023-06, with the labels that each got.

#568 chore(apps/prod/buildbarn): disable head method
  apps/prod/buildbarn/release.yaml
Labels: approved

#569 Revert "chore(apps/prod/buildbarn): disable head method"
  apps/prod/buildbarn/release.yaml
Labels: approved

#570 Revert "Revert "chore(apps/prod/buildbarn): disable head method""
  apps/prod/buildbarn/release.yaml
Labels: approved

#573 Revert "Revert "Revert "chore(apps/prod/buildbarn): disable head method"""
  apps/prod/buildbarn/release.yaml
Labels: approved

#575 feat(apps/prod/buildbarn): readcache brc with buildbarn
  apps/prod/buildbarn/release.yaml
Labels: approved

#577 feat(cluster/gcp): add alert notifies
  clusters/gcp/flux-system/kustomization.yaml
  clusters/gcp/flux-system/notification.yaml
Labels: approved

#578 feat(apps/prod/jenkins/post/tidb): add canary files for configmap `bazel`
  apps/prod/jenkins/post/tidb/files/canary-bazel
  apps/prod/jenkins/post/tidb/files/canary-bazel-prepare-in-container.sh
  apps/prod/jenkins/post/tidb/kustomization.yaml
Labels: approved

#580 chore(apps/prod): update owners
  apps/prod/OWNERS
Labels: approved

#584 Update README.md
  README.md
Labels: approved

#585 Revert "Update README.md"
  README.md
Labels: approved

#586 refactor(charts/prow): split configmap from chart
  .github/workflows/charts_test-prow.yaml
  .github/workflows/test-data/prow/configs/config.yaml
  .github/workflows/test-data/prow/configs/job-1.yaml
  .github/workflows/test-data/prow/configs/plugins.yaml
  .github/workflows/test-data/prow/ct-values.yaml
  charts/buildbarn/Chart.yaml
  charts/buildbarn/values.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/_helpers.tpl
  charts/prow/templates/components/crier/deployment.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/hook/deployment.yaml
  charts/prow/templates/components/horologium/deployment.yaml
  charts/prow/templates/components/jenkins-operator/deployment.yaml
  charts/prow/templates/components/pipeline/deployment.yaml
  charts/prow/templates/components/prow-controller-manager/deployment.yaml
  charts/prow/templates/components/sinker/deployment.yaml
  charts/prow/templates/components/status-reconciler/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/templates/configmap-config.yaml
  charts/prow/templates/configmap-jobs.yaml
  charts/prow/templates/configmap-plugins.yaml
  charts/prow/templates/secret-github.yaml
  charts/prow/templates/secret-hmac.yaml
  charts/prow/templates/secret-persistent.yaml
  charts/prow/templates/third-plugins/deployment.yaml
  charts/prow/values.yaml
Labels: approved

#587 refactor(apps/dev/prow): first deploy configmaps then deploy release
  apps/dev/prow/post.yaml
  apps/dev/prow/post/kustomization.yaml
  apps/dev/prow/post/label-sync-cronjob.yaml
  apps/dev/prow/pre.yaml
  apps/dev/prow/pre/configs/README.md
  apps/dev/prow/pre/configs/config.yaml
  apps/dev/prow/pre/configs/external_plugins_config.yaml
  apps/dev/prow/pre/configs/kustomization.yaml
  apps/dev/prow/pre/configs/labels.yaml
  apps/dev/prow/pre/configs/plugins.yaml
  apps/dev/prow/pre/kustomization.yaml
  apps/dev/prow/release.yaml
  apps/dev/prow/release/gce-ingress.yaml
  apps/dev/prow/release/release.yaml
Labels: approved

#588 fix(apps/dev/prow): fix configmap names and add secret generation
  .gitignore
  apps/dev/prow/post/label-sync-cronjob.yaml
  apps/dev/prow/pre.yaml
  apps/dev/prow/pre/configs/kustomization.yaml
  apps/dev/prow/pre/kustomization.yaml
  apps/dev/prow/pre/secrets.yaml
  apps/dev/prow/release/release.yaml
Labels: approved

#589 fix(apps/dev/prow/pre): fix secrets.yaml
  apps/dev/prow/pre/secrets.yaml
Labels: approved

#590 fix(apps/dev/prow/pre): fix subsitide for multi lines
  apps/dev/prow/pre/secrets.yaml
  apps/dev/prow/release/release.yaml
  clusters/dev/README.md
Labels: approved

#591 fix(apps/dev/prow): fix for external plugins volumns
  apps/dev/prow/pre/configs/kustomization.yaml
  apps/dev/prow/release/release.yaml
Labels: approved

#592 fix(apps/dev/prow/release): fix plugin config cli options for ti-community-tars plugin
  apps/dev/prow/release/release.yaml
Labels: approved

#593 refactor(charts/prow): refactor prow persistent credentials
  charts/prow/Chart.yaml
  charts/prow/templates/components/crier/deployment.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/status-reconciler/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/values.yaml
Labels: approved

#594 feat(apps/dev/prow): add gcs credential secret and use it in release
  apps/dev/prow/pre/secrets.yaml
  apps/dev/prow/release/release.yaml
Labels: approved

#595 refactor(apps/gcp/prow): deploy configmap and secret before helm release
  apps/gcp/kustomization.yaml
  apps/gcp/prow-crd.yaml
  apps/gcp/prow/kustomization.yaml
  apps/gcp/prow/post/kustomization.yaml
  apps/gcp/prow/pre.yaml
  apps/gcp/prow/pre/kustomization.yaml
  apps/gcp/prow/pre/prow-configs.yaml
  apps/gcp/prow/pre/prow-jobs.yaml
  apps/gcp/prow/pre/secrets.yaml
  apps/gcp/prow/release.yaml
  apps/gcp/prow/release/gce-ingress.yaml
  apps/gcp/prow/release/release.yaml
Labels: approved

#596 Revert "Revert "chore(apps/prod/prow/release): bump hook image to `ticommunityinfra/hook:v20230608-bd4b41b`""
  apps/gcp/prow/release/release.yaml
Labels: approved

#598 feat(apps/dev/prow/release): bump image for hook component
  apps/dev/prow-crd.yaml
  apps/dev/prow/release/release.yaml
  apps/gcp/prow-crd.yaml
  apps/staging/prow-crd.yaml
Labels: approved, size/XS

#600 feat(apps/gcp/prow/release): upgrade external plugin chatgpt
  apps/gcp/prow/release/release.yaml
Labels: approved, size/S

#599 feat(charts/prow): add additional env supports
  .github/workflows/test-data/prow/ct-values.yaml
  charts/prow/Chart.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/ghproxy/deployment.yaml
  charts/prow/templates/components/hook/deployment.yaml
  charts/prow/templates/components/horologium/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/templates/third-plugins/deployment.yaml
  charts/prow/values.yaml
Labels: approved, size/M

#601 feat(clusters/dev): add alert notifies
  apps/dev/prow/release/release.yaml
  clusters/dev/flux-system/kustomization.yaml
  clusters/dev/flux-system/notification.yaml
Labels: approved, size/L

#602 feat(apps/dev/prow/release): increase interval and timeout
  apps/dev/prow/release/release.yaml
Labels: approved, size/XS

#603 feat(apps/gcp/prow/release): increase interval and timeout
  apps/gcp/prow/release/release.yaml
Labels: approved, size/L

#604 fix(apps/gcp/prow/release): fix wrong cli options of chatgpt plugin
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#606 chore(apps/gcp/prow): add lgtm sticky for repos
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#607 fix(apps/prod/buildbarn): fix pvc size for storage shards
  apps/prod/buildbarn/release.yaml
Labels: approved, size/XS

#608 chore(apps/gcp/prow): add lgtm sticky repos
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#610 chore(apps/dev/prow): bump prow chart release to v0.9.3
  apps/dev/prow/release/release.yaml
Labels: lgtm, approved, size/XS

#611 chore(apps/gcp/prow/pre/chatgpt): add `default` task for document repos
  apps/gcp/prow/pre/chatgpt/tasks.yaml
Labels: approved, size/S

#612 chore(apps/gcp/prow/pre/chatgpt): increase `max_response_tokens` for docs repos
  apps/gcp/prow/pre/chatgpt/tasks.yaml
Labels: approved, size/XS

#613 update the default user prompt for docs repo
  apps/gcp/prow/pre/chatgpt/tasks.yaml
Labels: approved, size/S

#614 chore(apps/prod/tekton): add ingress for event listenser
  apps/prod/tekton/configs.yaml
  apps/prod/tekton/configs/triggers/event-listener.yaml
  apps/prod/tekton/configs/triggers/ingress-event-listener.yaml
  apps/prod/tekton/configs/triggers/kustomization.yaml
  apps/prod/tekton/configs/triggers/templates/public.yaml
  apps/prod/tekton/setup.yaml
Labels: approved, size/M

#615 feature(apps/prod/prow): bump chatgpt to v20230621-df5abce
  apps/dev/prow/release/release.yaml
  apps/gcp/prow/pre/chatgpt/tasks.yaml
  apps/gcp/prow/release/release.yaml
Labels: approved, size/S

#616 feature(apps/prod/buildbarn): add ingress for buildbarn services
  apps/prod/buildbarn/release.yaml
  charts/buildbarn/values.yaml
Labels: approved, size/M

#617 fix(charts/buildbarn): fix ingress for frontend component
  apps/prod/buildbarn/release.yaml
  charts/buildbarn/Chart.yaml
  charts/buildbarn/templates/frontend/ingress.yaml
Labels: approved, size/XS

#618 fix(charts/buildbarn): fix ingress for frontend component
  apps/prod/buildbarn/release.yaml
  charts/buildbarn/Chart.yaml
  charts/buildbarn/templates/browser/ingress.yaml
  charts/buildbarn/templates/frontend/ingress.yaml
  charts/buildbarn/values.yaml
Labels: approved, size/M

#619 fix(charts/buildbarn): fix ingress for frontend component
  apps/prod/buildbarn/release.yaml
  charts/buildbarn/Chart.yaml
  charts/buildbarn/templates/frontend/ingress.yaml
Labels: approved, size/XS

#620 feature(apps/prod/buildbarn): use ingress class name
  apps/prod/buildbarn/release.yaml
Labels: approved, size/XS

#622 feature(apps/dev/prow/prow/release): bump hook's image tag to `v20230627-6c92121`
  apps/dev/prow/release/release.yaml
Labels: approved, size/XS

#623 feature(apps/dev/prow/prow/release): bump hook's image tag to `v20230627-6810132`
  apps/dev/prow/release/release.yaml
Labels: approved, size/XS

#626 Feature/apps/dev/bump prow hook image to test new approve 2
  apps/dev/prow/release/release.yaml
Labels: approved, size/XS

#628 fix(apps/gc/prow/pre): Migrate OpenAI task files to ti-community-infra/configs repo
  apps/gcp/prow/pre/chatgpt/tasks.yaml
  apps/gcp/prow/pre/kustomization.yaml
Labels: approved, size/M

#629 fix(apps/gc/prow/release): bump hook image tag to `v20230629-a95a424`
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#630 fix(apps/gc/prow/release): enable report for jenkins-operator
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#631 fix(apps/gc/prow/release): bump image of jenkins-operator to `v20230630-a19314f`
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS
