Repository PingCAP-QE/ee-ops, pull requests merged in 2023-07, with the labels that each got.

#632 feat(charts/prow): add kubeconfig secret support
  charts/prow/Chart.yaml
  charts/prow/templates/components/crier/deployment.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/hook/deployment.yaml
  charts/prow/templates/components/horologium/deployment.yaml
  charts/prow/templates/components/jenkins-operator/deployment.yaml
  charts/prow/templates/components/prow-controller-manager/deployment.yaml
  charts/prow/templates/components/sinker/deployment.yaml
  charts/prow/templates/components/status-reconciler/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
  charts/prow/values.yaml
Labels: approved, size/L

#634 feature(apps/gcp/prow/prow/release): add `--kubeconfig` options to components
  apps/gcp/prow/release/release.yaml
Labels: approved, size/S

#635 chore(apps/gc/prow/release): add lgtm sticky repo `pingcap/tidb-binlog`
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#636 fix(apps/gcp/prow/release): add gcs credential to `prow-test-pods` namespace
  apps/gcp/prow/pre/kustomization.yaml
  apps/gcp/prow/pre/secrets-test-pods.yaml
Labels: approved, size/S

#637 feat(apps/prod/prow-worker): setup prow job's pod namespace
  apps/prod/kustomization.yaml
  apps/prod/prow-worker/kustomization.yaml
  apps/prod/prow-worker/namespace.yaml
  apps/prod/prow-worker/pvc.yaml
Labels: approved, size/M

#640 fix(apps/dev/prow/release): bump tide image
  apps/dev/prow/release/release.yaml
Labels: approved, size/XS

#642 fix(charts/prow): add container probes for tide component
  charts/prow/Chart.yaml
  charts/prow/templates/components/deck/deployment.yaml
  charts/prow/templates/components/tide/deployment.yaml
Labels: approved, size/S

#644 fix(apps/prod/tekton/setup): fix the issue arm64 image for prune
  apps/prod/prow-worker/gencred.sh
  apps/prod/tekton/setup/kustomization.yaml
  apps/prod/tekton/setup/operator-release.yaml
Labels: approved, size/XXL

#645 fix(apps/dev/prow/release): bump hook image
  apps/dev/prow/release/release.yaml
Labels: approved, size/XS

#654 feat: add ccache pvc
  apps/prod/ccache-pvc/base/kustomization.yaml
  apps/prod/ccache-pvc/base/pvc.yaml
  apps/prod/ccache-pvc/kustomization.yaml
  apps/prod/ccache-pvc/platforms/linux-amd64/kustomization.yaml
  apps/prod/ccache-pvc/platforms/linux-arm64/kustomization.yaml
  apps/prod/kustomization.yaml
Labels: lgtm, approved, size/M
