Repository PingCAP-QE/ee-ops, pull requests merged in 2023-03, with the labels that each got.

#418 fix: fix jenkins k8s plugin version error
  apps/prod/jenkins/release/values-controller-plugins.yaml
Labels: lgtm

#420 chore(infrastructure/prod/rook-ceph): add 3 cluster nodes
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#421 chore(infrastructure/prod/rook-ceph): add 1 cluster nodes
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved, do-not-merge/hold

#422 chore(apps/prod/greenhouse): increase greenhouse data size to to 15Ti
  apps/prod/greenhouse/release.yaml
Labels: approved, do-not-merge/hold

#423 feat(apps/prod/jenkins/post/tidb): add deno-dir pvc
  apps/prod/jenkins/post/tidb/pvc.yaml
Labels: lgtm, approved

#424 feat(apps/staging/ats): switch to nginx LB by url hash
  apps/staging/ats/release.yaml
  apps/staging/jenkins/post/tidb/files/bazel
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-call-jenkins.yaml
Labels: approved

#417 docs(cluster): update docs for clusters
  README.md
  clusters/staging/README.md
Labels: lgtm, approved

#425 fix(apps/staging/ats): fix ingress paths
  apps/staging/ats/release.yaml
Labels: approved

#426 fix(apps/staging/ats): fix nginx 413 too large error
  apps/staging/ats/release.yaml
Labels: approved

#427 chore(apps/staging/ats): update ats config override
  apps/staging/ats/config-override/remap.config
Labels: approved

#428 perf(stagings): increase read/write performance for ceph rbd
  apps/staging/ats/release.yaml
  infrastructure/staging/rook-ceph/release-cluster.yaml
Labels: approved

#431 feat(apps/staging/prow,apps/staging/tekton): add tekton ko build pipeline for repo `ti-community-infra/test-infra`
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-curl-call-tekton-pipeline-run.yaml
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-curl-call-tekton-task-run.yaml
  apps/staging/prow/post/configs/jobs/kustomization.yaml
  apps/staging/tekton/configs/pipelines/ko-build-test-infra.yaml
  apps/staging/tekton/configs/pipelines/kustomization.yaml
  apps/staging/tekton/configs/tasks/ko-test-infra.yaml
  apps/staging/tekton/configs/tasks/ko.yaml
  apps/staging/tekton/configs/tasks/kustomization.yaml
Labels: approved

#434 chore(apps/staging/tekton/setup): bump tekton operator to `v0.66.0`
  apps/staging/tekton/setup/kustomization.yaml
  apps/staging/tekton/setup/operator-config.yaml
  apps/staging/tekton/setup/operator-release.yaml
Labels: approved

#435 fix(apps/staging/tekton/setup): fix tekton config field `spec.pipeline.default-timeout-minutes`
  apps/staging/tekton/setup/operator-config.yaml
Labels: approved

#436 fix(apps/staging/prow/release): upgrade prow basic components
  apps/dev/prow/release/release.yaml
  apps/staging/prow/release/release.yaml
Labels: approved

#437 fix(apps/dev/prow/configs): update `lgtm` config to test the hacked `lgtm` built-in plugin
  apps/dev/prow/post/configs/config.yaml
Labels: approved

#439 fix(apps/staging/tekton/setup): rollback tekton operator to `v0.65.1`
  apps/staging/tekton/setup/kustomization.yaml
Labels: approved

#440 feat(apps/staging/tekton): add deployments of tekton operator to health checks
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
  apps/staging/tekton/setup.yaml
Labels: approved, do-not-merge/hold

#441 fix(apps/staging/prow/release): upgrade prow hook component
  apps/dev/prow/release/release.yaml
  apps/staging/prow/release/release.yaml
Labels: approved

#442 fix(apps/staging/prow/release): upgrade prow hook component
  apps/dev/prow/post/configs/config.yaml
  apps/dev/prow/post/configs/plugins.yaml
  apps/dev/prow/release/release.yaml
  apps/staging/prow/release/release.yaml
Labels: approved
