Repository PingCAP-QE/ee-ops, pull requests merged in 2023-05, with the labels that each got.

#508 fix apps of staging and dev: prow chatgpt plugin
  apps/dev/prow/post/configs/plugins.yaml
  apps/dev/prow/release/release.yaml
  apps/staging/prow/release/release.yaml
Labels: approved, size/M

#507 feat(apps/staging/sec-service): Update the image repository
  apps/staging/sec-service/sec-agent/deployment.yaml
  apps/staging/sec-service/sec-server/deployment.yaml
Labels: ok-to-test, lgtm, approved, size/XS

#509 fix(apps/gcp/prow): bump chatgpt plugin image to v20230428-10c1653
  apps/gcp/prow/release/release.yaml
Labels: approved, size/XS

#510 feat(apps/staging/tekton): try to implement mutli arch image building
  apps/staging/tekton/configs/pipelines/kaniko-build.yaml
  apps/staging/tekton/setup/operator-config.yaml
Labels: approved, size/M

#512 feat(apps/staging): add dogfooding codescan security tekton tasks
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
  apps/staging/tekton/configs/cluster-tasks/codescan-security-prow.yaml
  apps/staging/tekton/configs/cluster-tasks/codescan-security.yaml
  apps/staging/tekton/configs/cluster-tasks/kustomization.yaml
  apps/staging/tekton/configs/pipelines/codescan-security.yaml
  apps/staging/tekton/configs/pipelines/kustomization.yaml
Labels: approved, size/L

#513 feat(apps/staging): add buildfarm app to research dev-test
  apps/staging/buildfarm/configs/config.yaml
  apps/staging/buildfarm/kustomization.yaml
  apps/staging/buildfarm/redis-cluster.yaml
  apps/staging/buildfarm/server.yaml
  apps/staging/buildfarm/shard-worker.yaml
  apps/staging/kustomization.yaml
Labels: approved, size/L

#511 Add security scanning capability
  apps/prod/kustomization.yaml
  apps/prod/sec-service.yaml
  apps/prod/sec-service/kustomization.yaml
  apps/prod/sec-service/rbac.yaml
  apps/prod/sec-service/redis/deployment.yaml
  apps/prod/sec-service/redis/kustomization.yaml
  apps/prod/sec-service/redis/pvc.yaml
  apps/prod/sec-service/redis/service.yaml
  apps/prod/sec-service/sec-agent/deployment.yaml
  apps/prod/sec-service/sec-agent/kustomization.yaml
  apps/prod/sec-service/sec-server/deployment.yaml
  apps/prod/sec-service/sec-server/kustomization.yaml
  apps/prod/sec-service/sec-server/service.yaml
Labels: ok-to-test, lgtm, approved, size/L

#515 fix(apps/staing/prow/post/configs/jobs): fix tekton job `codescan-security`
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-prowjob.yaml
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
Labels: approved, size/XS

#516 fix(apps/staing/prow/post/configs/jobs): fix tekton job `codescan-security`
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
Labels: approved, size/XS

#517 fix(apps/staing/prow/post/configs/jobs): fix tekton job `codescan-security`
  apps/staging/prow/post/configs/jobs/PingCAP-QE/ee-ops/job-tekton-pipeline-spec.yaml
  apps/staging/tekton/configs/pipelines/codescan-security.yaml
Labels: approved, size/XS

#514 fix(apps/gcp/prow): bump chatgpt plugin image to v20230505-46ce180
  apps/staging/prow/release/release.yaml
Labels: approved, size/XS

#518 fix(apps/staing/prow/release): fix needs-rebase external plugin pod's ports
  apps/staging/prow/release/release.yaml
  charts/prow/values.yaml
Labels: approved, size/XS

#520 chore(apps/staging/buildfarm): build buildfarm config
  apps/staging/buildfarm/configs/config.yaml
Labels: approved, size/S

#521 fix(apps/staging/buildfarm): add namespace for kustomization
  apps/staging/buildfarm/kustomization.yaml
Labels: approved, size/XS

#522 fix(apps/staging/buildfarm): fix services ports and increase replicas for workers
  apps/staging/buildfarm/server.yaml
  apps/staging/buildfarm/shard-worker.yaml
Labels: approved, size/S

#523 fix(apps/staging/buildfarm): fix services ports and increase replicas for workers
  apps/staging/buildfarm/configs/config.yaml
  apps/staging/buildfarm/server.yaml
  apps/staging/buildfarm/shard-worker.yaml
Labels: approved, size/S

#524 fix(apps/staging/buildfarm): fix config
  apps/staging/buildfarm/configs/config.yaml
Labels: approved, size/XS

#525 chore(apps/staging/buildfarm): increase cpu and memory resource for shard workers
  apps/staging/buildfarm/configs/config.yaml
  apps/staging/buildfarm/redis-cluster.yaml
  apps/staging/buildfarm/server.yaml
  apps/staging/buildfarm/shard-worker.yaml
Labels: approved, size/S

#526 refactor(apps/staging/tekton/configs/cluster-tasks): update tasks for new design of security service
  apps/staging/tekton/configs/cluster-tasks/codescan-security-prow.yaml
  apps/staging/tekton/configs/cluster-tasks/codescan-security.yaml
Labels: lgtm, approved, size/S

#527 fix: feat(apps/staging/sec-service): Update the image repository
  apps/prod/sec-service/sec-agent/deployment.yaml
  apps/prod/sec-service/sec-server/deployment.yaml
Labels: ok-to-test, lgtm, approved, size/XS

#529 update: change agent image version.
  apps/prod/sec-service/sec-agent/deployment.yaml
Labels: ok-to-test, approved, size/XS

#530 update: change agent image version.
  apps/prod/sec-service/sec-agent/deployment.yaml
Labels: ok-to-test, lgtm, approved, size/XS

#531 fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-1216aa4`
  apps/staging/prow/release/release.yaml
Labels: approved, size/XS

#532 fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-97a0d53`
  apps/staging/prow/release/release.yaml
Labels: approved, size/XS

#533 fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-15ca628`
  apps/staging/prow/release/release.yaml
Labels: lgtm, approved, size/XS

#534 fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-d5656f4`
  apps/staging/prow/release/release.yaml
Labels: lgtm, approved, size/XS

#535 fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-0058871`
  apps/staging/prow/release/release.yaml
Labels: lgtm, approved, size/XS

#536 fix(apps/staging/prow/release): bump chatgpt plugin's image tag to `v20230511-565d3ec`
  apps/staging/prow/release/release.yaml
Labels: lgtm, approved, size/XS

#540 feat(apps/prod/buildfarm): init application deployment
  apps/prod/buildfarm/configs/config.yaml
  apps/prod/buildfarm/kustomization.yaml
  apps/prod/buildfarm/pvc.yaml
  apps/prod/buildfarm/redis-cluster.yaml
  apps/prod/buildfarm/server.yaml
  apps/prod/buildfarm/shard-worker.yaml
  apps/prod/kustomization.yaml
  apps/staging/kustomization.yaml
Labels: approved

#542 feat(apps/prod/jenkins): add ns jenkins-tiflash-schrodinger
  apps/prod/jenkins/post/kustomization.yaml
  apps/prod/jenkins/post/tiflash-schrodinger/kustomization.yaml
  apps/prod/jenkins/post/tiflash-schrodinger/namespace.yaml
Labels: lgtm, approved

#543 feat(chats): add helm chart `buildbarn`
  charts/buildbarn/Chart.yaml
  charts/buildbarn/README.md
  charts/buildbarn/templates/_helpers.tpl
  charts/buildbarn/templates/browser/configmap.yaml
  charts/buildbarn/templates/browser/deployment.yaml
  charts/buildbarn/templates/browser/ingress.yaml
  charts/buildbarn/templates/browser/podmonitor.yaml
  charts/buildbarn/templates/browser/service.yaml
  charts/buildbarn/templates/configmap.yaml
  charts/buildbarn/templates/frontend/configmap.yaml
  charts/buildbarn/templates/frontend/deployment.yaml
  charts/buildbarn/templates/frontend/podmonitor.yaml
  charts/buildbarn/templates/frontend/service.yaml
  charts/buildbarn/templates/scheduler/configmap.yaml
  charts/buildbarn/templates/scheduler/deployment.yaml
  charts/buildbarn/templates/scheduler/ingress.yaml
  charts/buildbarn/templates/scheduler/podmonitor.yaml
  charts/buildbarn/templates/scheduler/service.yaml
  charts/buildbarn/templates/serviceaccount.yaml
  charts/buildbarn/templates/storage/configmap.yaml
  charts/buildbarn/templates/storage/podmonitor.yaml
  charts/buildbarn/templates/storage/service.yaml
  charts/buildbarn/templates/storage/statefulset.yaml
  charts/buildbarn/templates/worker/configmap.yaml
  charts/buildbarn/templates/worker/deployment.yaml
  charts/buildbarn/templates/worker/podmonitor.yaml
  charts/buildbarn/values.yaml
Labels: approved

#544 chore(apps/prod): delete buildfarm
  apps/prod/buildfarm/configs/config.yaml
  apps/prod/buildfarm/kustomization.yaml
  apps/prod/buildfarm/pvc.yaml
  apps/prod/buildfarm/redis-cluster.yaml
  apps/prod/buildfarm/server.yaml
  apps/prod/buildfarm/shard-worker.yaml
  apps/prod/kustomization.yaml
Labels: approved

#545 fix(apps/gcp/prow/release): decrease chatgpt message limit
  apps/gcp/prow/release/release.yaml
Labels: approved

#546 feat(apps/prod/tekton): add tekton component
  apps/prod/kustomization.yaml
  apps/prod/tekton/configs.yaml
  apps/prod/tekton/configs/cluster-tasks/codescan-security-prow.yaml
  apps/prod/tekton/configs/cluster-tasks/codescan-security.yaml
  apps/prod/tekton/configs/cluster-tasks/kustomization.yaml
  apps/prod/tekton/configs/kustomization.yaml
  apps/prod/tekton/configs/namespace.yaml
  apps/prod/tekton/configs/pipelines/codescan-security.yaml
  apps/prod/tekton/configs/pipelines/kaniko-build.yaml
  apps/prod/tekton/configs/pipelines/ko-build-test-infra.yaml
  apps/prod/tekton/configs/pipelines/kustomization.yaml
  apps/prod/tekton/configs/pipelines/pipeline1.yaml
  apps/prod/tekton/configs/tasks/echo.yaml
  apps/prod/tekton/configs/tasks/git-clone.yaml
  apps/prod/tekton/configs/tasks/github-set-status.yaml
  apps/prod/tekton/configs/tasks/golang-build.yaml
  apps/prod/tekton/configs/tasks/golang-test.yaml
  apps/prod/tekton/configs/tasks/ko-test-infra.yaml
  apps/prod/tekton/configs/tasks/kubernetes-actions.yaml
  apps/prod/tekton/configs/tasks/kustomization.yaml
  apps/prod/tekton/configs/tasks/multi-arch-image-push.yaml
  apps/prod/tekton/configs/triggers/bindings/github-pr.yaml
  apps/prod/tekton/configs/triggers/bindings/kustomization.yaml
  apps/prod/tekton/configs/triggers/event-listener.yaml
  apps/prod/tekton/configs/triggers/kustomization.yaml
  apps/prod/tekton/configs/triggers/rbac.yaml
  apps/prod/tekton/configs/triggers/templates/kustomization.yaml
  apps/prod/tekton/configs/triggers/templates/public.yaml
  apps/prod/tekton/configs/triggers/triggers/kustomization.yaml
  apps/prod/tekton/configs/triggers/triggers/public.yaml
  apps/prod/tekton/kustomization.yaml
  apps/prod/tekton/setup.yaml
  apps/prod/tekton/setup/ingress-dashboard.yaml
  apps/prod/tekton/setup/kustomization.yaml
  apps/prod/tekton/setup/namespace.yaml
  apps/prod/tekton/setup/operator-config.yaml
Labels: approved

#547 fix(apps/prod/tekton): add annotations for namespaces
  apps/prod/tekton/setup.yaml
Labels: approved

#548 fix(apps/prod/tekton): fix kustomization source path
  apps/prod/tekton/setup.yaml
Labels: approved

#550 fix(apps/prod/tekton): add annotations for workspace namespace
  apps/prod/tekton/configs.yaml
Labels: approved

#552 fix(apps/prod/buildbarn): fix helm release
  apps/prod/buildbarn/configs/common.jsonnet
  apps/prod/buildbarn/kustomization.yaml
  apps/prod/buildbarn/kustomize-config.yaml
  apps/prod/buildbarn/release.yaml
Labels: approved

#555 feat(apps/gcp/tekton/configs/pipelines): add pipeline `kaniko-build`
  apps/prod/tekton/configs/pipelines/kustomization.yaml
Labels: approved

#557 feat(apps/prod/buildbarn): switch pvc storageclass to ceph-block for storage statfulset
  apps/prod/buildbarn/release.yaml
Labels: approved

#558 fix(gcp/prow/release): bump image ticommunityinfra/tichi-issue-triage-plugin to `v2.4.3`
  apps/dev/prow/release/release.yaml
  apps/gcp/prow/release/release.yaml
Labels: approved

#559 fix(apps/charts/buildbarn): migrate ingress to frontend instead of sheculder
  apps/prod/buildbarn/release.yaml
  charts/buildbarn/Chart.yaml
  charts/buildbarn/templates/frontend/ingress.yaml
  charts/buildbarn/templates/storage/statefulset.yaml
  charts/buildbarn/values.yaml
Labels: approved

#560 Revert "feat(apps/prod/buildbarn): switch pvc storageclass to ceph-block for storage statfulset"
  apps/prod/buildbarn/release.yaml
Labels: approved

#410 chore(staging): update nginx ingress svc node ports
  infrastructure/staging/nginx/release.yaml
Labels: approved

#556 refactor: Add Observer Pattern Switch
  apps/prod/sec-service/sec-agent/deployment.yaml
  apps/prod/sec-service/sec-server/deployment.yaml
Labels: lgtm, approved

#561 refactor(infrastructure/prod/rook-ceph): replace node
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#562 refactor(infrastructure/prod/rook-ceph): disable admission controller
  infrastructure/prod/rook-ceph/release-operator.yaml
Labels: approved

#563 refactor(infrastructure/prod/rook-ceph): replace 2 nodes
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#564 refactor(infrastructure/prod/rook-ceph): replace 7 nodes
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#565 refactor(infrastructure/prod/rook-ceph): delete node10
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved

#566 refactor(infrastructure/prod/rook-ceph): delete node9
  infrastructure/prod/rook-ceph/release-cluster.yaml
Labels: approved
